W.hat = NULL
#target = c("RMST", "survival.probability"),
#target = "survival.probability"
#horizon = NULL
failure.times = NULL
num.trees = 2000
sample.weights = NULL
clusters = NULL
equalize.cluster.weights = FALSE
sample.fraction = 0.5
min.node.size = 5
honesty = TRUE
honesty.fraction = 0.5
honesty.prune.leaves = TRUE
alpha = 0.05
imbalance.penalty = 0
stabilize.splits = TRUE
ci.group.size = 2
tune.parameters = "none"
compute.oob.predictions = TRUE
num.threads = NULL
seed = runif(1, 0, .Machine$integer.max)
mahalanobis = TRUE
prediction.type = "Kaplan-Meier"
mtry = min(ceiling(sqrt(p)), p)